name         'smarchive-gradle'
version      '0.1.2'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-gradle'
source       'https://github.com/smarchive/puppet-gradle'
summary      'Puppet module for installing the Gradle build tool from the official distribution'
description  'This module installs the Gradle build tool from the official project site. Check README.md for details.'
dependency   'smarchive/archive', '>=0.1.0'
